---
name: Brother-QL Web
version: 0.1.2
slug: brother-ql_web
description: "Web UI for print labels on Brother Label Printers"
url: "https://github.com/dersimn/brother_ql_web"
init: false
arch:
  - amd64
  - aarch64
ports:
  8013/tcp: 8013
ports_description:
  8013/tcp: Web interface
# ingress: true
# ingress_port: 8013
options:
  printer: 'tcp://192.168.1.98:9100'
  model: QL-500
  default_label_size: 62
  default_orientation: standard
  log_level: info
schema:
  printer: str
  model: list(QL-500|QL-550|QL-560|QL-570|QL-580N|QL-650TD|QL-700|QL-710W|QL-720NW|QL-810W|QL-820NWB|QL-1050|QL-1060N)?
  default_label_size: list(12|29|38|50|54|62|102|17x54|17x87|23x23|29x42|29x90|39x90|39x48|52x29|62x29|62x100|102x51|102x152|d12|d24|d58)?
  default_orientation: list(standard|rotated)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
map:
  - config:rw
  - ssl
usb: true